sudo: required
dist: trusty

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

language: node_js

matrix:
  include:
    - node_js: 4
      env: BUILD=0
    - node_js: 4
      env: BUILD=1
  fast_finish: true

before_script:
  - 'if [ "$BUILD" = "1" ]; then cd ..; fi'
  - 'if [ "$BUILD" = "1" ]; then git clone https://github.com/ckeditor/ckeditor-presets.git; fi'
  - 'if [ "$BUILD" = "1" ]; then cd ckeditor-presets; fi'
  - 'if [ "$BUILD" = "1" ]; then git fetch --all; fi'
  - 'if [ "$BUILD" = "1" ]; then git checkout master; fi'
  - 'if [ "$BUILD" = "1" ]; then git reset --hard origin/master; fi'
  - 'if [ "$BUILD" = "1" ]; then git submodule update --init; fi'
  - 'if [ "$BUILD" = "1" ]; then ./build.sh full all -t; fi'
  - 'sh -e /etc/init.d/xvfb start'
  - 'export DISPLAY=:99.0'
  - 'npm install benderjs-cli -g'

script: bender run -c bender.ci.js
